
import { RouteRecord, StaffMember, StaffStatus, ZoneStatus } from './types';

// --- BASE DE DATOS MAESTRA DE PERSONAL (UNIFICADA v19) ---
export const STAFF_DB: { [key: string]: StaffMember } = {
  // --- MAÑANA ---
  'PEREZ_RO': { id: '32887', name: 'PEREZ RODRIGO', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'MAÑANA' },
  'FORNOS': { id: '16654', name: 'FORNOS JORGE', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'CORDERO': { id: '33796', name: 'CORDERO ROQ', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'IGLESIAS_J': { id: '9991', name: 'IGLESIAS JOSE', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'GODOY_GU': { id: '30725', name: 'GODOY GUSTAVO', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'MAÑANA' },
  'MARTINEZ_L': { id: '30955', name: 'MARTINEZ LEONEL', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'DUARTE_D': { id: '30720', name: 'DUARTE DIEGO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'PIMENTEL_D': { id: '31925', name: 'PIMENTEL DIEGO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'DESPALANQUE': { id: '30718', name: 'DESPALANQUE GUSTA', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'MAÑANA' },
  'GALARZA_M': { id: '31032', name: 'GALARZA MATIAS', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'GUAYAN_C': { id: '30778', name: 'GUAYAN CARLOS', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'MAÑANA' },
  'COCERES_J': { id: '31154', name: 'COCERES JUAN', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'GUIDO_D': { id: '37934', name: 'GUIDO DAMIAN', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'ARRIOLA_D': { id: '31150', name: 'ARRIOLA DANIEL', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'SANTUCHO_M': { id: '36893', name: 'SANTUCHO MATIAS', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'COCERES_JULIO': { id: 'C-JUL', name: 'COCERES JULIO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'LOPEZ_O': { id: '30905', name: 'LOPEZ OMAR', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'MAÑANA' },
  'GARBET_D': { id: '30898', name: 'GARBET DIEGO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'ARDILES_J': { id: '30881', name: 'ARDILES JAVIER', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'FRANCO_L': { id: '30896', name: 'FRANCO LUIS', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'ROMERO_C': { id: '28747', name: 'ROMERO CLAUDIO', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'MAÑANA' },
  'DARI_M': { id: '30717', name: 'DARI MARTIN', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'GREEN_L': { id: '30729', name: 'GREEN LUIS', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'MAÑANA' },
  'ACUNA_G': { id: '30921', name: 'ACUÑA GUILLERMO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'SAMUDIO_N': { id: '31236', name: 'SAMUDIO NESTOR', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'CACERES_M': { id: '30926', name: 'CACERES MIGUEL', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'CACERES_V': { id: '9415', name: 'CACERES VICENTE', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'CEJAS_A': { id: '30715', name: 'CEJAS ALEJANDRO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'FERNANDEZ_G': { id: '31192', name: 'FERNANDEZ GABRIEL', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'MAÑANA' },
  'BUSTOS_P': { id: '32824', name: 'BUSTOS PABLO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'GODOY_GO': { id: '30899', name: 'GODOY GONZALO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'GARCIA_A': { id: '30939', name: 'GARCIA ALEJANDRO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'PINTOS_E': { id: '31331', name: 'PINTOS EDUARDO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'ESPINOLA_P': { id: '30892', name: 'ESPINOLA PABLO', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'MAÑANA' },
  'CARRANZA_W': { id: '30888', name: 'CARRANZA WALTER', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'PELLIZA_A': { id: '29391', name: 'PELLIZA ANDRES', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'BASTI_D': { id: '33913', name: 'BASTI DIEGO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'ZALAZAR_M': { id: 'Z-MAR', name: 'ZALAZAR MARTIN', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'MAÑANA' },
  'LUQUE_M': { id: '30215', name: 'LUQUE MATIAS', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'SERAFINI_M': { id: '33450', name: 'SERAFINI MAXI', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'MAÑANA' },
  'LONANO_A': { id: '31820', name: 'LONANO ARIEL', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'DOMINGUEZ_L': { id: '30936', name: 'DOMINGUEZ LOREN', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'PAREDES_F_M': { id: '35727', name: 'PAREDES FACUNDO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'QUINTEROS_C': { id: '30997', name: 'QUINTEROS CRISTIAN', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'MAÑANA' },
  'VEGA_I': { id: '38897', name: 'VEGA IVAN', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'SINESI_M': { id: '38548', name: 'SINESI MAXI', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'CAPRIO_J': { id: '30840', name: 'CAPRIO JUAN', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'TEZEIRA_P': { id: '30872', name: 'TEZEIRA PABLO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'STEBNER_F': { id: '30805', name: 'STEBNER FERNAN', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'MAÑANA' },
  'LOPEZ_A': { id: '31155', name: 'LOPEZ ARIEL', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'MAÑANA' },
  'RODRIGUEZ_C': { id: '30800', name: 'RODRIGUEZ CRISTIAN', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'TISEIRA_D': { id: '30807', name: 'TISEIRA DIEGO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'MANSILLA_R': { id: '30879', name: 'MANSILLA RAM', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'FERNANDEZ_E': { id: '31840', name: 'FERNANDEZ EMANUEL', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'TORREZ_L': { id: '31451', name: 'TORREZ LUIS', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'MAÑANA' },
  'MAIDANA_C': { id: '34706', name: 'MAIDANA CARLOS', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'ALFONSO_H': { id: '30923', name: 'ALFONSO HUGO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'GRANEROS_H': { id: '39392', name: 'GRANEROS HECTOR', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'PEREYRA_D_M': { id: '39232', name: 'PEREYRA DIEGO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'HERNANDEZ_A': { id: '35000', name: 'HERNANDEZ ARIEL', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'FARINA_M': { id: '30827', name: 'FARIÑA MANUEL', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'MAÑANA' },
  'DIPRETORO_M_MAQ': { id: '31160', name: 'DIPRETORO MATIAS', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'GUERRA_D': { id: '28760', name: 'GUERRA DARIO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'SANTOLIN_J': { id: '41309', name: 'SANTOLIN JUAN', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'ROBLAS_C': { id: '30859', name: 'ROJAS CLAUDIO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'AGUINAGA': { id: '31039', name: 'AGUINAGA', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'MAÑANA' },
  'SANTOS_G': { id: '25194', name: 'SANTOS GABRIEL', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'RODRIGUEZ_J': { id: '30973', name: 'RODRIGUEZ JAVIER', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'MAÑANA' },
  'QUIROGA_J': { id: '37587', name: 'QUIROGA JULIO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'CARRIZO_F': { id: '30889', name: 'CARRIZO FACUNDO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'BRAVO_L': { id: '30627', name: 'BRAVO LUCAS', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'SALVA_C': { id: 'S-CLA', name: 'SALVA CLAUDIO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'ARREDONDO_C': { id: '30751', name: 'ARREDONDO CRISTIAN', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'MAÑANA' },
  'FINOS_S': { id: '30883', name: 'FINOS SEBASTIAN', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'MAÑANA' },
  'HERRERA_P_M': { id: '30945', name: 'HERRERA PABLO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'CAMPERO_E': { id: '32999', name: 'CAMPERO EZEQUIEL', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'USINGER_C': { id: '30979', name: 'USINGER CARLOS', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'STEPCHICH_A': { id: '30977', name: 'STEPCHICH ANGEL', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'ESPINOSA_M': { id: '16083', name: 'ESPINOSA MARIO', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'MAÑANA' },
  'ESPINOSA_I': { id: '39470', name: 'ESPINOSA ISAC', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'OSORIO_E': { id: '30961', name: 'OSORIO EMANUEL', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'DIDI_DIEGO_C': { id: '35652', name: 'DI DIEGO CRISTIAN', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'GONZALEZ_G': { id: '31037', name: 'GONZALEZ GUILLERMO', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'MAÑANA' },
  'FERNANDEZ_C': { id: '30895', name: 'FERNANDEZ C.', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'MAÑANA' },
  'LESCANO_LUC': { id: '37603', name: 'LESCANO LUCAS', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'LEDESMA_H': { id: '31153', name: 'LEDESMA HUGO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'MORILLA_F': { id: '22903', name: 'MORILLA FABIAN', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'PIMENTEL_J': { id: '30701', name: 'PIMENTEL JUAN', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'MAÑANA' },
  'ORELLANA_F': { id: '30851', name: 'ORELLANA FERN', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'ALMIRON_A': { id: '29587', name: 'ALMIRON ALEJANDRO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'NUNEZ_E': { id: '35032', name: 'NUÑEZ EMILIANO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'ACOSTA_A': { id: '31852', name: 'ACOSTA ALEJANDRO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'SCAPICCHI': { id: '30645', name: 'SCAPICCHI LEONEL', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'MAÑANA' },
  'GOROSITO_C': { id: '29484', name: 'GOROSITO CRISTIAN', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'ESCOBAR_A': { id: '37933', name: 'ESCOBAR ARIEL', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'MOREIRA_D': { id: '34712', name: 'MOREIRA DANIEL', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'WALLHIMER': { id: '31778', name: 'WALLHIMER ALE', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'PRONE_H': { id: '27727', name: 'PRONE HUGO', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'MAÑANA' },
  'ROBLEDO_A': { id: '30858', name: 'ROBLEDO ANDRES', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'ACOSTA_L': { id: 'A-LE', name: 'ACOSTA LEANDRO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'MONSERRAT': { id: 'M-EL', name: 'MONSERRAT ELISEO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'RODRIGUEZ_F_M': { id: 'R-FR', name: 'RODRIGUEZ FRANCO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'CASTRO_R': { id: 'C-RA', name: 'CASTRO RAMON', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'GONZALEZ_M_M': { id: '31169', name: 'GONZALEZ MARCELO', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'MAÑANA' },
  'ARREDONDO_G': { id: '31819', name: 'ARREDONDO GONZA', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'CARRIZO_L': { id: '34389', name: 'CARRIZO LEANDRO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'CISTERNA_M': { id: '28793', name: 'CISTERNA MARTIN', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'CARRIZO_R_M': { id: 'C-RO', name: 'CARRIZO RODRIGO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'VILLALBA_E_M': { id: '30809', name: 'VILLALBA EDUARDO', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'MAÑANA' },
  'HERRERA_B': { id: '34994', name: 'HERRERA BRIAN', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'GONZALEZ_D': { id: '34231', name: 'GONZALEZ DAVID', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'ALARCON_G': { id: '27817', name: 'ALARCON GERMAN', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'CARBALLO_E': { id: '29505', name: 'CARBALLO EMANUEL', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'CACERES_C_M': { id: '32009', name: 'CACERES CARLOS', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'MAÑANA' },
  'ARRIETA_L': { id: '31392', name: 'ARRIETA LEANDRO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'GOMEZ_M_M': { id: '32228', name: 'GOMEZ MARCELO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'GAUTO_M': { id: '25176', name: 'GAUTO MIGUEL', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'LEDESMA_M_M': { id: '22979', name: 'LEDESMA MARCELO', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'MAÑANA' },
  'LOPEZ_M_M': { id: '27108', name: 'LOPEZ MARIO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'GAUNA_L': { id: '41497', name: 'GAUNA LUCAS', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'ROLDAN_D': { id: '30916', name: 'ROLDAN DAVID', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'SAAVEDRA_A': { id: '30802', name: 'SAAVEDRA ARTURO', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'MAÑANA' },
  'PUCHETA_J': { id: '31914', name: 'PUCHETA JAVIER', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'ARREDONDO_OC_M': { id: '32997', name: 'ARREDONDO O CRIST', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'GARNICA_F': { id: '34413', name: 'GARNICA FERNANDO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'SANTOS_M_M': { id: '20964', name: 'SANTOS MARIO', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'MAÑANA' },
  'SANTOS_AL': { id: '32612', name: 'SANTOS ALEXIS', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'DIAZ_A_M': { id: '41310', name: 'DIAZ AGUSTIN', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'CAMPOS_R': { id: '23478', name: 'CAMPOS RUBEN', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'SANTOS_JU': { id: '22116', name: 'SANTOS JUAN', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'ESPINDOLA_W': { id: '30770', name: 'ESPINDOLA WALTER', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'MAÑANA' },
  'GALVEZ_J': { id: '13272', name: 'GALVEZ JOSE', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'VILLALBA_AL': { id: '31143', name: 'VILLALBA ALE', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'ZAYAS': { id: '34101', name: 'ZAYAS', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },
  'BLOCK_F': { id: '39233', name: 'BLOCK FEDERICO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'MAÑANA' },

  // --- TARDE ---
  'DIAZ_J_29309': { id: '29309', name: 'DIAZ JORGE', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'TARDE' },
  'CALIBA_J_32596': { id: '32596', name: 'CALIBA JONA', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'AGUERO_J_32596': { id: '32596_2', name: 'AGÜERO JONA', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'ROMERO_M_32572': { id: '32572', name: 'ROMERO MAXI', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'PAREDES_F_32177': { id: '32177', name: 'PAREDES FEDERICO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'OLMOS_O_11480': { id: '11480', name: 'OLMOS OMAR', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'TARDE' },
  'DIAZ_M_30935': { id: '30935', name: 'DIAZ MARCOS', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'CASTIGLIO_33924': { id: '33924', name: 'CASTIGLIO NE F', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'FERREYRA_C_32579': { id: '32579', name: 'FERREYRA CLAUDIO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'GONZALEZ_J_32393': { id: '32393', name: 'GONZALEZ JORGE', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'LUNA_J_15447': { id: '15447', name: 'LUNA JORGE', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'TARDE' },
  'LOPEZ_C_37604': { id: '37604', name: 'LOPEZ CRISTIAN', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'MEZA_C_29351': { id: '29351', name: 'MEZA CRISTIAN', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'AMARILLA_C_41273': { id: '41273', name: 'AMARILLA CRISTIAN', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'LUNGE_M_32793': { id: '32793', name: 'LUNGE MAXI', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'RIVERO_E_23150': { id: '23150', name: 'RIVERO EMILIO', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'TARDE' },
  'KNUTTSEN_G_31177': { id: '31177', name: 'KNUTTSEN GABI', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'MENDEZ_H_30906': { id: '30906', name: 'MENDEZ HUGO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'ALARCON_M_25433': { id: '25433', name: 'ALARCON M.', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'COLASANTI_D_36165': { id: '36165', name: 'COLASANTI DIEGO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'ARAOZ_E_31178': { id: '31178', name: 'ARAOZ ESTE', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'TARDE' },
  'ARREDONDO_F_32882': { id: '32882', name: 'ARREDONDO FER', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'ARREDONDO_OC_30751': { id: '30751', name: 'ARREDONDO O C', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'ARREDONDO_R_30752': { id: '30752', name: 'ARREDONDO ROB', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'MILLICAY_G_31921': { id: '31921', name: 'MILLICAY GABI', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'MARTINEZ_J_30954': { id: '30954', name: 'MARTINEZ J.', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'TARDE' },
  'MOLAS_N_30786': { id: '30786', name: 'MOLAS NICO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'AQUINO_E_30749': { id: '30749', name: 'AQUINO ELBIO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'BENITEZ_J_31239': { id: '31239', name: 'BENITEZ JOSE', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'IBARRA_C_30780': { id: '30780', name: 'IBARRA CARLOS', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'TARDE' },
  'LEIVA_V_37591': { id: '37591', name: 'LEIVA VICTOR', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'LEGUIZAMO_31841': { id: '31841', name: 'LEGUIZAMO N M', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'BARUA_M_31180': { id: '31180', name: 'BARUA MAGU', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'GODOY_P_30776': { id: '30776', name: 'GODOY PEDRO', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'TARDE' },
  'VILLANUEVA_31035': { id: '31035', name: 'VILLANUEVA', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'GIORGIO_L_30775': { id: '30775', name: 'GIORGIO LEONAR', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'NILO_G_31040': { id: '31040', name: 'NILO GONZALO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'ZARATE_M_32427': { id: '32427', name: 'ZARATE MARCELO', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'TARDE' },
  'CORONEL_I_33937': { id: '33937', name: 'CORONEL IVAN', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'SANCHEZ_C_31885': { id: '31885', name: 'SANCHEZ CRISTIAN', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'AVEJERA_H_30884': { id: '30884', name: 'AVEJERA HUGO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'MORALES_A_32573': { id: '32573', name: 'MORALES ANTO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'AGUINAGA_J_31039': { id: '31039', name: 'AGUINAGA JARA', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'TARDE' },
  'FARIAS_J_34711': { id: '34711', name: 'FARIAS JAVIER', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'ALCARAZ_S_33925': { id: '33925', name: 'ALCARAZ SER', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'LANNI_C_30691': { id: '30691', name: 'LANNI CLAU', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'VALDEZ_M_31165': { id: '31165', name: 'VALDEZ MIGUEL', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'TARDE' },
  'HERRERA_D_31847': { id: '31847', name: 'HERRERA DANI', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'GARCIA_A_31826': { id: '31826', name: 'GARCIA ALEJANDRO', status: StaffStatus.ABSENT, role: 'AUXILIAR', address: 'F', preferredShift: 'TARDE' },
  'GARAYO_P_31923': { id: '31923', name: 'GARAYO PATRI', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'HURTADO_N_31606': { id: '31606', name: 'HURTADO NICOLAS', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'GONZALEZ_J_30830': { id: '30830', name: 'GONZALEZ JORGE', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'TARDE' },
  'MELO_I_31038': { id: '31038', name: 'MELO ISAIAS', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'TARDE' },
  'MARTINEZ_P_31033': { id: '31033', name: 'MARTINEZ PABLO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'CABRAL_J_37608': { id: '37608', name: 'CABRAL JUAN', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'LATORRE_M_31998': { id: '31998', name: 'LATORRE MARTIN', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'GOROSITO_31034': { id: '31034', name: 'GOROSITO', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'TARDE' },
  'ROLON_F_30974': { id: '30974', name: 'ROLON FER', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'VARGAS_K_32810': { id: '32810', name: 'VARGAS KEVIN', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'DIPRETORO_S_30766': { id: '30766', name: 'DI PRETORO SAN', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'CALTABIANO_J_30711': { id: '30711', name: 'CALTABIANO JAVI', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'TARDE' },
  'GOMEZ_S_41278': { id: '41278', name: 'GOMEZ SIMON', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'SALDANA_F_30917': { id: '30917', name: 'SALDAÑA FRANCISCO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'BLANCO_A_37605': { id: '37605', name: 'BLANCO ALEJANDRO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'HURTADO_A_36851': { id: '36851', name: 'HURTADO ALE', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'RASCHELLA_J_30855': { id: '30855', name: 'RASCHELLA JUAN', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'TARDE' },
  'ALMIRON_J_24042': { id: '24042', name: 'ALMIRON JULIO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'GOMEZ_J_30900': { id: '30900', name: 'GOMEZ JOSE', status: StaffStatus.ABSENT, role: 'AUXILIAR', address: 'F', preferredShift: 'TARDE' },
  'GIAMPIETRI_J_30940': { id: '30940', name: 'GIAMPIETRI JORGE', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'FERREYRA_M_30938': { id: '30938', name: 'FERREYRA MARCELO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'CASAREZ_J_30820': { id: '30820', name: 'CASAREZ JULIO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'RODRIGUEZ_G_31965': { id: '31965', name: 'RODRIGUEZ GUSTAVO', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'TARDE' },
  'GIMENEZ_A_30941': { id: '30941', name: 'GIMENEZ ALE', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'HEIS_G_29679': { id: '29679', name: 'HEIS GUIDO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'ESPINDOLA_V_30937': { id: '30937', name: 'ESPINDOLA VIC', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'AMARILLA_CL_31346': { id: '31346', name: 'AMARILLA CLAUDIO', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'TARDE' },
  'BARROS_A_31822': { id: '31822', name: 'BARROS ALAN', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'FUGASSA_N_31903': { id: '31903', name: 'FUGASSA NICOLAS', status: StaffStatus.ABSENT, role: 'AUXILIAR', address: 'F', preferredShift: 'TARDE' },
  'MARTINEZ_V_30956': { id: '30956', name: 'MARTINEZ V.', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'ALLENDE_W_32883': { id: '32883', name: 'ALLENDE WAL', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'GONZALEZ_J_31158': { id: '31158', name: 'GONZALEZ JORGE', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'TARDE' },
  'ROJAS_R_32805': { id: '32805', name: 'ROJAS RAMON', status: StaffStatus.ABSENT, role: 'AUXILIAR', address: 'F', preferredShift: 'TARDE' },
  'RAMIREZ_N_32683': { id: '32683', name: 'RAMIREZ N', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'HERNANDEZ_T_41274': { id: '41274', name: 'HERNANDEZ TOMAS', status: StaffStatus.ABSENT, role: 'AUXILIAR', address: 'F', preferredShift: 'TARDE' },
  'ORTIZ_U_30792': { id: '30792', name: 'ORTIZ ULISES', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'AVALOS_H_31182': { id: '31182', name: 'AVALOS HECTOR', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'FALCON_G_22938': { id: '22938', name: 'FALCON GABRIEL', status: StaffStatus.ABSENT, role: 'CHOFER', address: 'F', preferredShift: 'TARDE' },
  'ROBLEDO_M_16725': { id: '16725', name: 'ROBLEDO MIGUEL', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'RIVERO_D_30915': { id: '30915', name: 'RIVERO DIEGO', status: StaffStatus.ABSENT, role: 'AUXILIAR', address: 'F', preferredShift: 'TARDE' },
  'PEREZ_O_30796': { id: '30796', name: 'PEREZ ORLANDO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'DIPRETORO_SE_30826': { id: '30826', name: 'DI PRETORO SEBA', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'STROIA_R_31188': { id: '31188', name: 'STROIA RUBEN ALFREDO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'SPAGNOLO_L_32892': { id: '32892', name: 'SPAGNOLO LEO', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'TARDE' },
  'LASTRA_L_32890': { id: '32890', name: 'LASTRA LAUT', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'OCAMPOS_M_32071': { id: '32071', name: 'OCAMPOS MATIAS', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'MARUSSI_M_32881': { id: '32881', name: 'MARUSSI MAURO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'DIPRETORO_M_31161': { id: '31161', name: 'DI PRETORO M', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'TARDE' },
  'ROMERO_R_37610': { id: '37610', name: 'ROMERO ROBER', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'JEREZ_J_37593': { id: '37593', name: 'JEREZ JONATAN', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'GOMEZ_C_37616': { id: '37616', name: 'GOMEZ CARLOS', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'ALCARAZ_25201': { id: '25201', name: 'ALCARAZ', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'PEREZ_C_32534': { id: '32534', name: 'PEREZ CARLOS', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'PEREZ_C_30795': { id: '30795', name: 'PEREZ CARLOS (B)', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'CARDOZO_R_30822': { id: '30822', name: 'CARDOZO RODRIGO', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'CANTEROS_S_33182': { id: '33182', name: 'CANTEROS SERG', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'PEREZ_J_34707': { id: '34707', name: 'PEREZ JONATAN', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'DIPRETORO_F_30765': { id: '30765', name: 'DI PRETORO FER', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },
  'DIPRETORO_FR_32254': { id: '32254', name: 'DI PRETORO FR', status: StaffStatus.PRESENT, role: 'AUXILIAR', preferredShift: 'TARDE' },

  // --- NOCHE / REPASO ---
  'SANCHEZ_29088': { id: '29088', name: 'SANCHEZ MARIO', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'NOCHE' },
  'BERGARA_M': { id: 'B-BER', name: 'BERGARA M', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'NOCHE' },
  'MENDOZA_R': { id: 'M-MEN', name: 'MENDOZA R', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'NOCHE' },
  'PABLO_K': { id: 'P-KRA', name: 'PABLO K', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'NOCHE' },
  'MEROLLI_J': { id: 'M-MER', name: 'MEROLLI J', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'NOCHE' },
  'BARRAZA_A': { id: 'B-BAR', name: 'BARRAZA A', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'NOCHE' },
  'CALDERON_D': { id: 'C-CAL', name: 'CALDERON D', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'NOCHE' },
  'GIMENEZ_R': { id: 'G-GIM', name: 'GIMENEZ R', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'NOCHE' },
  'ACHILLI_M': { id: 'A-ACH', name: 'ACHILLI M', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'NOCHE' },
  'YUN_M': { id: 'Y-YUN', name: 'YUN M', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'NOCHE' },
  'MORA_A': { id: 'M-MOR', name: 'MORA A', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'NOCHE' },
  'CASTELAR_M': { id: 'C-CAS', name: 'CASTELAR M', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'NOCHE' },
  'FARIAS_M': { id: 'F-FAR', name: 'FARIAS M', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'NOCHE' },
  'VILLAGRA_S': { id: 'V-VIL', name: 'VILLAGRA S', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'NOCHE' },
  'PEREYRA_A': { id: 'P-PER', name: 'PEREYRA A', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'NOCHE' },
  'MARTIN_H': { id: 'M-MAR', name: 'MARTIN H', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'NOCHE' },
  'MIRAMON': { id: 'M-MIR', name: 'MIRAMON', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'TARDE' },
  'PAEZ_N': { id: 'P-PAE', name: 'PAEZ NAEL', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'TARDE' },
  'CANTARELLA': { id: 'C-CAN', name: 'CANTARELLA', status: StaffStatus.PRESENT, role: 'CHOFER', preferredShift: 'TARDE' }
};

// --- RUTAS MAÑANA ---
export const MANANA_MASTER_DATA: any[] = [
  { zone: 'RN 31A/B', interno: '352', domain: 'AF349UD', driver: 'PEREZ_RO', aux1: 'FORNOS', aux2: 'CORDERO', aux3: 'IGLESIAS_J' },
  { zone: 'RN 31', interno: '155', domain: 'NJL635', driver: 'GODOY_GU', aux1: 'MARTINEZ_L', aux2: 'DUARTE_D', aux3: 'PIMENTEL_D', repChofer: 'DESPALANQUE', report: 'GALARZA MATIAS 31032' },
  { zone: 'RN 40', interno: '343', domain: 'AF169DM', ref: '18', driver: 'GUAYAN_C', aux1: 'COCERES_J', aux2: 'GUIDO_D', aux3: 'ARRIOLA_D', aux4: 'SANTUCHO_M', report: 'COCERES JULIO' },
  { zone: 'RN 41', interno: '342', domain: 'AF169DP', driver: 'LOPEZ_O', aux1: 'GARBET_D', aux2: 'ARDILES_J', aux3: 'FRANCO_L', repChofer: 'ROMERO_C', repAux1: 'DARI_M' },
  { zone: 'RN 43', interno: '347', domain: 'AF169DN', driver: 'GREEN_L', aux1: 'ACUNA_G', aux2: 'SAMUDIO_N', aux3: 'CACERES_M', aux4: 'CACERES_V', report: 'CEJAS ALEJANDRO 30715' },
  { zone: 'RN 44', interno: '341', domain: 'AF169DH', driver: 'FERNANDEZ_G', aux1: 'BUSTOS_P', aux2: 'GODOY_GO', aux3: 'GARCIA_A', aux4: 'PINTOS_E' },
  { zone: 'RN 46', interno: '18', domain: 'NHR395', driver: 'ESPINOLA_P', aux1: 'CARRANZA_W', aux2: 'PELLIZA_A', aux3: 'BASTI_D', repChofer: 'ZALAZAR_M', repAux1: 'LUQUE_M', ton: '6.8' },
  { zone: 'RN 47B', interno: '340', domain: 'AF169DJ', driver: 'SERAFINI_M', aux1: 'LONANO_A', aux2: 'DOMINGUEZ_L', aux3: 'PAREDES_F_M' },
  { zone: 'RN 47', interno: '354', domain: 'AF349UG', ref: '354', driver: 'QUINTEROS_C', aux1: 'VEGA_I', aux2: 'SINESI_M', aux3: 'CAPRIO_J', aux4: 'TEZEIRA_P', repChofer: 'STEBNER_F' },
  { zone: 'RN 48', interno: '146', domain: 'NJL617', driver: 'LOPEZ_A', aux1: 'RODRIGUEZ_C', aux2: 'TISEIRA_D', aux3: 'MANSILLA_R', aux4: 'FERNANDEZ_E' },
  { zone: 'RN 49', interno: '154', domain: 'NJL634', ref: '322', driver: 'TORREZ_L', aux1: 'MAIDANA_C', aux2: 'ALFONSO_H', aux3: 'GRANEROS_H', aux4: 'PEREYRA_D_M', report: 'HERNANDEZ ARIEL 35000', ton: '8.3' },
  { zone: 'RN 50', interno: '322', domain: 'AE242HN', status: ZoneStatus.INCOMPLETE, driver: 'FARINA_M', aux1: 'DIPRETORO_M_MAQ', aux2: 'GUERRA_D', aux3: 'SANTOLIN_J', aux4: 'ROJAS_C', repChofer: 'AGUINAGA', repAux1: 'SANTOS_G', report: 'QUEDÓ DE 826 Y 827 DE 891 A DONATO. 823 DE 895 A 891.' },
  { zone: 'RN 51', interno: '332', domain: 'AE738OI', driver: 'RODRIGUEZ_J', aux1: 'QUIROGA_J', aux2: 'CARRIZO_F', aux3: 'BRAVO_L', aux4: 'SALVA_C', repChofer: 'ARREDONDO_C' },
  { zone: 'RN 52', interno: '349', domain: 'AF169DL', driver: 'FINOS_S', aux1: 'HERRERA_P_M', aux2: 'CAMPERO_E', aux3: 'USINGER_C', aux4: 'STEPCHICH_A' },
  { zone: 'RN 53', interno: '351', domain: 'AF349UF', driver: 'ESPINOSA_M', aux1: 'ESPINOSA_I', aux2: 'OSORIO_E', aux3: 'DIDI_DIEGO_C', repChofer: 'GONZALEZ_G' },
  { zone: 'RN 54', interno: '353', domain: 'AF349UE', driver: 'FERNANDEZ_C', aux1: 'LESCANO_LUC', aux2: 'LEDESMA_H', aux3: 'MORILLA_F' },
  { zone: 'RN 55', interno: '145', domain: 'NJL615', driver: 'PIMENTEL_J', aux1: 'ORELLANA_F', aux2: 'ALMIRON_A', aux3: 'NUNEZ_E', aux4: 'ACOSTA_A' },
  { zone: 'RN 57', interno: '321', domain: 'AE242HH', driver: 'SCAPICCHI', aux1: 'GOROSITO_C', aux2: 'ESCOBAR_A', aux3: 'MOREIRA_D', repChofer: 'WALLHIMER' },
  { zone: 'RN 58', interno: '346', domain: 'AF169DI', driver: 'PRONE_H', aux1: 'ROBLEDO_A', aux2: 'ACOSTA_L', aux3: 'MONSERRAT', aux4: 'RODRIGUEZ_F_M', repChofer: 'CASTRO_R' },
  { zone: 'RN 60', interno: '149', domain: 'NJL620', driver: 'GONZALEZ_M_M', aux1: 'ARREDONDO_G', aux2: 'CARRIZO_L', aux3: 'CISTERNA_M', repChofer: 'CARRIZO_R_M' },
  { zone: 'RN 61', interno: '7', domain: 'NHR382', driver: 'VILLALBA_E_M', aux1: 'HERRERA_B', aux2: 'GONZALEZ_D', aux3: 'ALARCON_G', aux4: 'CARBALLO_E' },
  { zone: 'RN 64', interno: '333', domain: 'AE783OH', driver: 'CACERES_C_M', aux1: 'ARRIETA_L', aux2: 'GOMEZ_M_M', aux3: 'GAUTO_M' },
  { zone: 'RN 65', interno: '158', domain: 'NJL633', driver: 'LEDESMA_M_M', aux1: 'LOPEZ_M_M', aux2: 'GAUNA_L', aux3: 'ROLDAN_D' },
  { zone: 'RN 66', interno: '329', domain: 'AE242HI', driver: 'SAAVEDRA_A', aux1: 'PUCHETA_J', aux2: 'ARREDONDO_OC_M', aux3: 'GARNICA_F' },
  { zone: 'RN 69', interno: '165', domain: 'ONE629', ref: '326', driver: 'SANTOS_M_M', aux1: 'SANTOS_AL', aux2: 'DIAZ_A_M', aux3: 'CAMPOS_R', aux4: 'SANTOS_JU' },
  { zone: 'RN 70', interno: '335', domain: 'AE738OG', driver: 'ESPINDOLA_W', aux1: 'GALVEZ_J', aux2: 'VILLALBA_AL', aux3: 'ZAYAS', repChofer: 'BLOCK_F' }
];

// --- RUTAS TARDE ---
export const TARDE_MASTER_DATA: any[] = [
  { zone: 'RN 1', interno: '332', domain: 'AE738OI', time: '12:15', driver: 'DIAZ_J_29309', aux1: 'CALIBA_J_32596', aux2: 'AGUERO_J_32596', aux3: 'ROMERO_M_32572', aux4: 'PAREDES_F_32177' },
  { zone: 'RN 4', interno: '340', domain: 'AF169DJ', time: '12:20', driver: 'OLMOS_O_11480', aux1: 'DIAZ_M_30935', aux2: 'CASTIGLIO_33924', aux3: 'FERREYRA_C_32579', aux4: 'GONZALEZ_J_32393' },
  { zone: 'RN 6', interno: '343', domain: 'AF169DM', time: '12:10', driver: 'LUNA_J_15447', aux1: 'LOPEZ_C_37604', aux2: 'MEZA_C_29351', aux3: 'AMARILLA_C_41273', aux4: 'LUNGE_M_32793' },
  { zone: 'RN 7', interno: '351', domain: 'AF349UF', time: '12:45', driver: 'RIVERO_E_23150', aux1: 'KNUTTSEN_G_31177', aux2: 'MENDEZ_H_30906', aux3: 'ALARCON_M_25433' },
  { zone: 'RN 13', interno: '349', domain: 'AF169DL', time: '12:30', aux1: 'COLASANTI_D_36165' },
  { zone: 'RN 14', interno: '145', domain: 'NJL615', time: '12:25', driver: 'ARAOZ_E_31178', aux1: 'ARREDONDO_F_32882', aux2: 'ARREDONDO_OC_30751', aux3: 'ARREDONDO_R_30752', aux4: 'MILLICAY_G_31921' },
  { zone: 'RN 15', interno: '158', domain: 'NJL633', time: '12:15', driver: 'MARTINEZ_J_30954', aux1: 'MOLAS_N_30786', aux2: 'AQUINO_E_30749', aux3: 'BENITEZ_J_31239' },
  { zone: 'RN 17', interno: '347', domain: 'AF169DN', time: '12:20', driver: 'IBARRA_C_30780', aux1: 'LEIVA_V_37591', aux2: 'LEGUIZAMO_31841', aux3: 'BARUA_M_31180' },
  { zone: 'RN 20', interno: '350', domain: 'AF169DO', time: '12:20', driver: 'GODOY_P_30776', aux1: 'VILLANUEVA_31035', aux2: 'GIORGIO_L_30775', aux3: 'NILO_G_31040' },
  { zone: 'RN 21', interno: '354', domain: 'AF349UG', time: '12:10', driver: 'ZARATE_M_32427', aux1: 'CORONEL_I_33937', aux2: 'SANCHEZ_C_31885', aux3: 'AVEJERA_H_30884', repChofer: 'MORALES_A_32573' },
  { zone: 'RN 23', interno: '353', domain: 'AF349UE', time: '12:10', driver: 'AGUINAGA_J_31039', aux1: 'FARIAS_J_34711', aux2: 'ALCARAZ_S_33925', aux3: 'LANNI_C_30691' },
  { zone: 'RN 27 BIS', interno: '342', domain: 'AF169DP', time: '12:40', driver: 'VALDEZ_M_31165', aux1: 'HERRERA_D_31847', aux2: 'GARCIA_A_31826', aux3: 'GARAYO_P_31923', repChofer: 'HURTADO_N_31606', report: 'GONZALEZ JORGE 30830 FERIADO' },
  { zone: 'RN 25', interno: '155', domain: 'NJL635', time: '12:30', driver: 'MELO_I_31038', aux1: 'MARTINEZ_P_31033', aux2: 'CABRAL_J_37608', aux3: 'LATORRE_M_31998' },
  { zone: 'RN 26', interno: '348', domain: 'AF169DK', time: '12:15', driver: 'GOROSITO_31034', aux1: 'ROLON_F_30974', aux2: 'VARGAS_K_32810', aux3: 'DIPRETORO_S_30766' },
  { zone: 'RN 28', interno: '165', domain: 'ONE629', time: '12:10', driver: 'CALTABIANO_J_30711', aux1: 'GOMEZ_S_41278', aux2: 'SALDANA_F_30917', aux3: 'BLANCO_A_37605', repChofer: 'HURTADO_A_36851' },
  { zone: 'RN 32B', interno: '327', domain: 'AE242HK', time: '12:15', driver: 'RASCHELLA_J_30855', aux1: 'ALMIRON_J_24042', aux2: 'GOMEZ_J_30900', aux3: 'GIAMPIETRI_J_30940', aux4: 'FERREYRA_M_30938', report: 'CASAREZ JULIO 30820 FERIADO' },
  { zone: 'RN 37', interno: '330', domain: 'AE242HO', time: '12:40', driver: 'RODRIGUEZ_G_31965', aux1: 'GIMENEZ_A_30941', aux2: 'HEIS_G_29679', aux3: 'ESPINDOLA_V_30937' },
  { zone: 'RN 42', interno: '341', domain: 'AF169DH', time: '12:20', driver: 'AMARILLA_CL_31346', aux1: 'BARROS_A_31822', aux2: 'FUGASSA_N_31903', aux3: 'MARTINEZ_V_30956', repChofer: 'ALLENDE_W_32883' },
  { zone: 'RN 59', interno: '333', domain: 'AE783OH', ref: '158', time: '12:25', driver: 'GONZALEZ_J_31158', aux1: 'ROJAS_R_32805', aux2: 'RAMIREZ_N_32683', aux3: 'HERNANDEZ_T_41274', report: 'ORTIZ ULISES 30792. AVALOS HECTOR 31182 FERIADO' },
  { zone: 'RN 59 BIS', interno: '7', domain: 'NHR382', time: '12:10', driver: 'FALCON_G_22938', aux1: 'ROBLEDO_M_16725', aux2: 'RIVERO_D_30915', aux3: 'PEREZ_O_30796', aux4: 'DIPRETORO_SE_30826', repChofer: 'STROIA_R_31188' },
  { zone: 'RN 62', interno: '352', domain: 'AF349UD', time: '12:15', driver: 'SPAGNOLO_L_32892', aux1: 'LASTRA_L_32890', aux2: 'OCAMPOS_M_32071', aux3: 'MARUSSI_M_32881' },
  { zone: 'RN 67', interno: '335', domain: 'AE738OG', time: '12:15', driver: 'DIPRETORO_M_31161', aux1: 'ROMERO_R_37610', aux2: 'JEREZ_J_37593', aux3: 'GOMEZ_C_37616' },
  { zone: '18A-18B-14A', interno: '329', domain: 'AE242HI', time: '12:50', aux1: 'ALCARAZ_25201', aux2: 'PEREZ_C_32534', aux3: 'PEREZ_C_30795', repChofer: 'CARDOZO_R_30822' },
  { zone: '7A-22A-25A', interno: '146', domain: 'NJL617', time: '12:05', aux1: 'CANTEROS_S_33182', aux2: 'PEREZ_J_34707', aux3: 'DIPRETORO_F_30765', aux4: 'DIPRETORO_FR_32254' }
];

// --- REPASO Y CARGA LATERAL (MAESTRO v19) ---
export const MANANA_REPASO_DATA: any[] = [
  { zone: 'REPASO 1', interno: '11', domain: 'NHR386' },
  { zone: 'REPASO 2', interno: '166', domain: 'ONE632' },
  { zone: 'REPASO 3', interno: '334', domain: 'AE738OH' },
  { zone: 'REPASO 4', interno: '160', domain: 'NJL604' },
  { zone: 'REPASO 5', interno: '35', domain: 'NHR466' },
  { zone: 'MONTE DON BOSCO', interno: '136', domain: 'AG989QO' },
  { zone: 'CARGA LATERAL RN 1', interno: '135', domain: 'AG989QO' },
  { zone: 'CARGA LATERAL RN 2', interno: '135', domain: 'AG989QO' },
  { zone: 'CARGA LATERAL RN 3', interno: '137' },
  { zone: 'REPOSICION DE TACHOS', interno: '501', domain: 'AC756FY' },
  { zone: 'TACHOS (VICENTE LOPEZ)', interno: '135' },
  { zone: 'EMPROLIJAMIENTO', interno: '330' },
  { zone: 'LA MATERA', interno: '18' },
  { zone: 'DELEG. BERNAL OESTE', interno: '158' },
  { zone: 'RN B/QUILMES', interno: '348' },
  { zone: 'RN LOS ALAMOS', interno: '341' },
  { zone: 'FINEXCOR / LYNCH', interno: '347' }
];

export const TARDE_REPASO_DATA: any[] = [
  { zone: 'REGIONAL OESTE', driver: 'MIRAMON' },
  { zone: 'CARGA LATERAL RN', interno: '133', domain: 'AE836YZ', driver: 'PAEZ_N' },
  { zone: 'CARGA LATERAL RN', interno: '160', domain: 'NJL604', driver: 'CANTARELLA' },
  { zone: 'CARGA LATERAL RN', interno: '166', domain: 'ONE632' },
  { zone: 'CARGA LATERAL RN 4', interno: '334', domain: 'AE738OH' },
  { zone: 'REPASO', interno: '35', domain: 'NHR466' },
  { zone: 'BOULEVARD', interno: '335', domain: 'AE738OG' }
];

export const NOCHE_REPASO_DATA: any[] = [
  { zone: 'CARGA LATERAL RN 8', interno: '137', domain: 'AG989QO', driver: 'SANCHEZ_29088' },
  { zone: 'CARGA LATERAL RN 9', interno: '134', domain: 'AF930EP', driver: 'BERGARA_M' },
  { zone: 'CARGA LATERAL RN 10', interno: '135', domain: 'AG989QO', driver: 'MENDOZA_R' },
  { zone: 'RECOLECCION CARGA TRASERA', interno: '334', domain: 'AE738OH', driver: 'PABLO_K' },
  { zone: 'QUILMES ZONA 11', interno: '166', domain: 'ONE632', driver: 'MEROLLI_J' },
  { zone: 'QUILMES CENTRO', interno: '501', domain: 'AC756FY', driver: 'BARRAZA_A' },
  { zone: 'URIBURU Y ESTACIONES', interno: '334', domain: 'AE738OH', driver: 'CALDERON_D' },
  { zone: 'LIMPIEZA DE CONTENEDORES', interno: '121', domain: 'KSD560', driver: 'GIMENEZ_R' },
  { zone: 'EMPORIO - SAN CAYETANO', interno: '145', domain: 'NJL615', driver: 'ACHILLI_M' },
  { zone: 'BOULEVARD', interno: '145', domain: 'NJL615', driver: 'YUN_M' },
  { zone: 'EMPROLIJAMIENTO ECOPUNTOS', interno: '136', domain: 'AG989QO', driver: 'MORA_A' },
  { zone: '15 DE DICIEMBRE', interno: '11', driver: 'CASTELAR_M' },
  { zone: 'REFUERZO T.N', driver: 'PEREYRA_A' },
  { zone: 'MOTOBARRIDO', driver: 'MARTIN_H' },
  { zone: 'REPASO - SOLANO - EZPELETA', interno: '35', domain: 'NHR466', driver: 'FARIAS_M' },
  { zone: 'REPASO QUILMES CENTRO-BERNAL', interno: '160', domain: 'NJL604', driver: 'VILLAGRA_S' }
];

export const NOCHE_MASTER_DATA: any[] = [
  { zone: 'RN 0', interno: '347' }, { zone: 'RN 2', interno: '340' }, { zone: 'RN 3', interno: '352' },
  { zone: 'RN 5', interno: '341' }, { zone: 'RN 8', interno: '351' }, { zone: 'RN 9', interno: '32' },
  { zone: 'RN 12', interno: '340' }, { zone: 'RN 16', interno: '18' }, { zone: 'RN 18', interno: '350' },
  { zone: 'RN 19', interno: '165' }, { zone: 'RN 24', interno: '342' }, { zone: 'RN 26A', interno: '327' },
  { zone: 'RN 27', interno: '328' }, { zone: 'RN 29', interno: '330' }, { zone: 'RN 29A', interno: '321' },
  { zone: 'RN 30', interno: '346' }, { zone: 'RN 32', interno: '328' }, { zone: 'RN 33', interno: '353' },
  { zone: 'RN 34', interno: '155' }, { zone: 'RN 35', interno: '335' }, { zone: 'RN 36', interno: '332' },
  { zone: 'RN 38', interno: '354' }, { zone: 'RN 39', interno: '348' }, { zone: 'RN 45', interno: '333' },
  { zone: 'RN 63', interno: '154' }
];

export const EXTRA_STAFF: StaffMember[] = Object.values(STAFF_DB);
export const MOCK_RECORDS: RouteRecord[] = [];
export const FLEET_MASTER_DATA = [];
